package silmex.apps.airdropcryptopoints.ui.theme

import androidx.compose.ui.graphics.Color

val MainBG = Color(0xFFF1F1F6)
val AltBG = Color(0xFFFEFEFE)
val WhiteText = Color(0xFFFEFEFE)
val AltBorder = Color(0xFF647B94)
val ShadeBackground = Color(0xFF7584EE)
val LearningShade = Color(0xFFE8E8E9)
val LearningBright = Color(0xFFC7C2FE)
val MainTextColor = Color(0xFF1E1E1E)
val OffTextColor = Color(0xFFBBBBC0)
val OffBGColor = Color(0xFFBCBCC1)
val SideTextColor = Color(0xFFF25D02)
val ButtonTextColor = Color(0xFF4737FE)
val NotUsedRed = Color(0xFFFE3A44)
val UsedGreen = Color(0xFF329F71)
val InvalidOrange = Color(0xFFF65C03)
val AlmostTransparent = Color(0x03FFFFFF)
val WithdrawalTextColor = Color(0xFF4737FE)
val ToastSucceded = Color(0xFFDAF4E1)
val ToastNotSuceded = Color(0xFFF4DFDA)
val FarmingProgressBG = Color(0xFF9086FE)
val FarmingProgressEndedBG = Color(0xFFC7C2FE)
val MiniBorder = Color(0xFF344054)